{% set name = "rosettasciio" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rosettasciio-{{ version }}.tar.gz
  sha256: 4c4beab05fc395663a44c1f3a0163f252efbde9971fbaa411155eb9570539e1c

build:
  number: 0

outputs:
  - name: rosettasciio-base
    build:
      skip: true  # [py<38]
    script: install.sh  # [not win]
    script: install.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - cython                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - python                                 # [build_platform != target_platform]
      host:
        - cython
        - pip
        - python
        - setuptools >=64.0
        - setuptools_scm>=8
        - wheel
      run:
        - python
        - dask-core >=2021.3.1
        - python-dateutil
        - numpy >=1.20.0
        - pint >=0.8
        - python-box >=6,<7
        - pyyaml
    test:
      imports:
        - rsciio
      commands:
        - pip check

  - name: rosettasciio
    build:
      skip: true  # [py<38]
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('rosettasciio-base', exact=True) }}
        - python
        # blockfile
        - scikit-image >=0.18
        # eds-stream
        - sparse
        # hdf5
        - h5py >=2.3
        # image
        - imageio >=2.16
        # Remove once imageio >2.32 is released
        - pillow <10.1.0
        # mrcz
        - mrcz
        - blosc
        # scalebar_export
        - matplotlib-scalebar
        - matplotlib-base >=3.5
        # speed
        - numba >=0.52
        # tiff
        - tifffile >=2020.2.16
        - imagecodecs >=2020.1.31
        # usid
        - pyUSID >=0.0.11
        # zspy
        - zarr
    test:
      imports:
        - rsciio
        - pytest --pyargs rsciio
      requires:
        - pip
        - pytest-xdist
        - pooch

about:
  home: https://hyperspy.org/rosettasciio
  summary: Reading and writing scientific file formats
  dev_url: https://github.com/hyperspy/rosettasciio
  license: GPL-3.0-or-later
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - ericpre
    - francisco-dlp
    - jlaehne
